### ISSUE TITLE
Memory allocation of x bytes failed.

### ISSUE THREAD

**Issue by infraorder** [ErikNatanael/knyst#22]
Hi there

Firstly, really enjoying trying out knyst.

I'm trying to modify a custom oscillator to use rlua to generate the wave, however facing an issue inside the unsafe here for instance:
https://github.com/ErikNatanael/knyst/blob/05e731c583588729da546cdc2536d07dab69acbf/knyst/src/graph.rs#L563

but I noticed anything that seems to allocate memory is failing, for example using a logger etc.

so, for instance, I have a rlua instance sitting in process:

```rust
impl Gen for OscillatorStream {
    fn process(&mut self, ctx: GenContext, _resources: &mut Resources) -> GenState {
        let sample_rate = ctx.sample_rate;
        self.lua.context(|lua_ctx| {
            for i in 0..ctx.block_size() {
                let t = interval * i as f32;
                let frequency = self.frequency.load(Ordering::Relaxed);

                let function: Function = lua_ctx.globals().get("wave").unwrap();
                let out0 = function.call::<_, ()>((t, frequency, self.phase)).unwrap();
                let out1 = function.call::<_, ()>((t, frequency, self.phase)).unwrap();

                ctx.outputs.write(out0, 0, i);
                ctx.outputs.write(out1, 1, i);
            }
        });

        self.seek_to(interval * (ctx.block_size() as f32));

        GenState::Continue
    }
}
```

but  anytime I call this method I get `memory allocation of x bytes failed`.

I guess what I'm asking is, is there a way around this or is this sort of a limitation I can't easily get around?

Many thanks!

**Comment by ErikNatanael** [comment]
Happy to hear you're enjoying knyst! As you've found out, allocation is not allowed on the audio thread. Knyst actually only enforces this on debug builds using [assert_no_alloc](https://github.com/Windfisch/rust-assert-no-alloc), but I guess it's possible that some part of your audio stack is sandboxing the audio thread from allocation. Unless you are running the Graph manually, `process` is called from the audio thread, usually managed by the audio driver/subsystem. What system and audio stack are you on? The way around this is to either
1. allocate everything you need up front, or
2. run the process on another thread and send the samples over some kind of channel, ideally a ring buffer. You'd need some buffering so latency will be higher, but you could start off with 2 times the block size and generate new samples on the helper thread as soon as there are spots free in the ring buffer. [rtrb](https://crates.io/crates/rtrb) has worked well for me, and also has a list of alternatives in the README. Just make sure the channel is allocation free and wait free.

Let me know if it turns out to segfault or panic even without allocation as that would be a bug.

 Just a heads up that I've been working on a large overhaul of the public API for some time and plan to release it within the next few weeks. It will massively simplify graph initialisation and interaction.

**Comment by infraorder** [comment]
Thanks for the help!

I found a way around it for now which was enabling the feature `debug-warn-on-alloc`.

I am indeed running in debug yeah, many thanks!
