### ISSUE TITLE
Is there a way to pause and resume a sphere or graph?

### ISSUE THREAD

**Issue by Tuurlijk** [ErikNatanael/knyst#27]
If not, what would it cost to implement such a feature?

**Comment by ErikNatanael** [comment]
It's not possible currently, but you could implement it by making a new AudioBackend with that functionality for a Sphere/top level graph. There may be side effects for certain scheduling operations that have to be tested though. 

Another way is to add a Gen which wraps a Graph and runs it or not based on some input. This is not straight forward using the Handle API since the Graph isn't directly exposed, but that could be easily fixed by adding a method to KnystCommands which returns the local Graph. Scheduling issues may occur with this approach as well.

Could you describe your use case in greater detail?

Den 1 november 2024 17:48:12 CET, Michiel Roos ***@***.***> skrev:

**Comment by Tuurlijk** [comment]
I have a 'session' defined a file. It consists of several tonesets that can change over time based on envelopes.

The session is meant to be played as a whole. But pausing / resuming / scrubbing would be fantastic.

**Comment by ErikNatanael** [comment]
In that case, I think the most versatile solution is to have a play head Gen which outputs the read position. You could use atomics or channels to communicate with the Gen from the outside and tell it to stop moving, or even change the speed or direction of it's movement (for your scrubbing). Then make every envelope take this as an input for where in the envelope you are.

If you want to completely stop the audio thread, and not just stop the play head and mute the output, you can free everything and then add it back when you want to start playing again. 

Would this be a satisfactory solution?

Den 1 november 2024 18:23:14 CET, Michiel Roos ***@***.***> skrev:

**Comment by Tuurlijk** [comment]
Sounds good. I'll have a go at it.
